package main

const (
	EnvNeverWriteProduction        = "GOENV_NEVER_WRITE_PRODUCTION"
	AmGoEnvAlwaysWrite      string = "AM_GO_ENV_ALWAYS_WRITE"
	AmGoEnvAlwaysUseJson    string = "AM_GO_ENV_ALWAYS_USE_JSON"
	AmGoEnvAlwaysUseYaml    string = "AM_GO_ENV_ALWAYS_USE_YAML"
	AmGoEnvAlwaysUseXml     string = "AM_GO_ENV_ALWAYS_USE_XML"
	AmGoEnvAlwaysUseToml    string = "AM_GO_ENV_ALWAYS_USE_TOML"
	AmGoEnvAlwaysUseIni     string = "AM_GO_ENV_ALWAYS_USE_INI"
	AmGoEnvAlwaysPrint      string = "AM_GO_ENV_ALWAYS_PRINT"
	AmGoEnvNeverDelete      string = "AM_GO_ENV_NEVER_DELETE"

	envFileDefault     string = ".env"
	envFileLocal       string = ".env.local"
	envFileDevelopment string = ".env.development"
	envFileProduction  string = ".env.production"

	outFormatJson string = ".json"
	outFormatYaml string = ".yaml"
	outFormatToml string = ".toml"
	outFormatIni  string = ".ini"
	outFormatXml  string = ".xml"

	argEnvFile  string = "file"
	argEnv      string = "env"
	argValue    string = "value"
	argAdd      string = "add"
	argRm       string = "rm"
	argProd     string = "prod"
	argHas      string = "has"
	argIs       string = "is"
	argVerbose  string = "vv"
	argVersion  string = "v"
	argWrite    string = "write"
	argJson     string = "json"
	argIni      string = "ini"
	argYaml     string = "yaml"
	argToml     string = "toml"
	argPrint    string = "print"
	argXml      string = "xml"
	argNot      string = "not"
	argInit     string = "init"
	argMkAll    string = "mkall"
	argCleanAll string = "cleanall"
)
